"""empty message

Revision ID: 3048fc4291f0
Revises: 
Create Date: 2017-09-19 22:47:13.664373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3048fc4291f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_details',
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('longitude', sa.Float(precision='10,6'), nullable=False),
    sa.Column('latitude', sa.Float(precision='9,6'), nullable=False),
    sa.Column('speed', sa.Float(precision='6,3'), nullable=False),
    sa.Column('color_r', sa.Integer(), nullable=False),
    sa.Column('color_g', sa.Integer(), nullable=False),
    sa.Column('color_b', sa.Integer(), nullable=False),
    sa.Column('temp', sa.Float(precision='6,3'), nullable=False),
    sa.Column('humidity', sa.Float(precision='6,3'), nullable=False),
    sa.Column('gas', sa.Float(precision='6,3'), nullable=False),
    sa.PrimaryKeyConstraint('car_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car_details')
    # ### end Alembic commands ###
