"""empty message

Revision ID: 81adc99bd02e
Revises: 
Create Date: 2017-10-06 02:51:40.375433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81adc99bd02e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_details',
    sa.Column('car_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('ch_1', sa.String(length=9), nullable=True),
    sa.Column('ch_2', sa.String(length=9), nullable=True),
    sa.Column('ch_3', sa.String(length=9), nullable=True),
    sa.Column('ch_4', sa.String(length=9), nullable=True),
    sa.Column('ch_5', sa.String(length=9), nullable=True),
    sa.Column('ch_6', sa.String(length=9), nullable=True),
    sa.Column('ch_7', sa.String(length=9), nullable=True),
    sa.Column('ch_8', sa.String(length=9), nullable=True),
    sa.Column('ch_9', sa.String(length=9), nullable=True),
    sa.Column('chh_10', sa.String(length=9), nullable=True),
    sa.Column('total_time', sa.String(length=9), nullable=True),
    sa.PrimaryKeyConstraint('car_id')
    )
    op.create_table('parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temp', sa.String(length=7), nullable=True),
    sa.Column('humid', sa.String(length=7), nullable=True),
    sa.Column('gas', sa.String(length=8), nullable=True),
    sa.Column('lon', sa.String(length=15), nullable=True),
    sa.Column('lat', sa.String(length=15), nullable=True),
    sa.Column('speed', sa.String(length=10), nullable=True),
    sa.Column('cr', sa.String(length=3), nullable=True),
    sa.Column('cg', sa.String(length=3), nullable=True),
    sa.Column('cb', sa.String(length=3), nullable=True),
    sa.Column('rt', sa.String(length=8), nullable=True),
    sa.Column('bat', sa.String(length=3), nullable=True),
    sa.Column('loca', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parameters')
    op.drop_table('car_details')
    # ### end Alembic commands ###
