"""empty message

Revision ID: 983586d4cd8e
Revises: 
Create Date: 2017-09-20 19:09:57.292723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '983586d4cd8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_details',
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('longitude', sa.String(), nullable=False),
    sa.Column('latitude', sa.String(), nullable=False),
    sa.Column('speed', sa.String(), nullable=False),
    sa.Column('color_r', sa.Integer(), nullable=False),
    sa.Column('color_g', sa.Integer(), nullable=False),
    sa.Column('color_b', sa.Integer(), nullable=False),
    sa.Column('temp', sa.String(), nullable=False),
    sa.Column('humidity', sa.String(), nullable=False),
    sa.Column('gas', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('car_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car_details')
    # ### end Alembic commands ###
